### ISSUE TITLE
MMU3 R4 compatibility

### ISSUE THREAD

**Issue by HonzaJaros** [davidkerny/BUZA-ULTIMULTI#7]
Hello,

could you confirm that ultimulti is fully compatible with new revision on printables. the R4?

With the official release and Shipping of mmu4 for MK4, is it going to be needed an update to R4 Standard of ultimulti for mk4?

As Průša mentioned, There was some extensive testing and changing some parts recently…. they just published R4 STLs

My kit will come soon, so I am thinking to print ultimulti and skip the printing the Prusa mmu3 printable parts if better than R4.

thanks for your feedback or update :)

**Comment by davidkerny** [comment]
Hi! 
The prusa mmu3 R4 update adresses these issues:
- Parts were optimized for the updated prusa print farm with MK4 IS printers instead of MK3S. Mainly tolerances of small openings have changed. This is not a concern for the home-printed parts. However, this is the reason all the part markings have changed.
- Selector blades have been re-positioned. Insufficiently clamped selector blades have been adressed in Ultimulti selector in the past already.
- Selector has openings for easier insertion of the bronze bushings. This hasnt been an issue in ultimulti + there are small holes for gluing the tubes in.
- Rightmost Idler shaft kept falling out. Already fixed in Ultimulti a long time ago.
- Taller electronics cover and the pd-addon board cover: These are just an ESD compliancy additions that are recommended, not mandatory. Interestingly enough, for the MK3.5 (which is also xBuddy driven ), it is not required to change even as a recommendation.
- The only mandatory R4 printed part for MMU3 are the newer buffer cassettes. (along the extruder printed parts included in the kit)

Since, Some of the features from Ultimulti have been used in MMU3 and vice-versa, both will do the job. 
I've been using both versions with the same level of reliability on the MK4.
Personally, I of course prefer the Ultimulti due to the control over what's happening inside and due to being biased, but ultimately, the decision is up to you ;)

**Comment by HonzaJaros** [comment]
Thank you david for comprehensive answer!

as a soon to be new owner of mmu3 could you please point out  in wiki  what part must be printed from Prusa as compulsory for ultimulti. I am little bit lost in those name files… 

thank you
